# Generated by Django 5.2.8 on 2025-12-04 11:31

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание для страницы категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Автогенерируемый слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(help_text='Одно-два предложения', max_length=200, verbose_name='Краткое описание')),
                ('content', mdeditor.fields.MDTextField(verbose_name='Содержание поста')),
                ('cover', models.FileField(null=True, upload_to='post_covers/', verbose_name='Обложка')),
                ('reading_time', models.IntegerField()),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('slug', models.SlugField(unique=True, verbose_name='Автогенерируемый слаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-pub_date'],
            },
        ),
    ]
