# Generated by Django 5.2.8 on 2026-01-16 12:41

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание для страницы категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Cлаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Одно-два предложения', max_length=200, verbose_name='Краткое описание')),
                ('content', mdeditor.fields.MDTextField(help_text="Используйте формат .md. \n        Доступные теги: 'p', 'h2',\n        'h3', 'h4', 'ul', 'ol', 'li',\n        'strong', 'em', 'a', 'code', 'pre', \n        'blockquote'", verbose_name='Содержание поста')),
                ('cover', models.FileField(blank=True, null=True, upload_to='post_covers/', verbose_name='Обложка')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('pub_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('edited_datetime', models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='blog.category', verbose_name='Категория')),
                ('recommended_posts', models.ManyToManyField(blank=True, help_text='Посты, которые рекомендуются после прочтения этого', to='blog.post', verbose_name='Рекомендуемые посты')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-pub_datetime'],
            },
        ),
    ]
