# Generated by Django 5.2.8 on 2026-01-04 14:08

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_remove_post_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommended_posts',
            field=models.ManyToManyField(blank=True, help_text='Посты, которые рекомендуются после прочтения этого', to='blog.post', verbose_name='Рекомендуемые посты'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='blog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=mdeditor.fields.MDTextField(help_text="Используйте формат .md. \n        Доступные теги: 'p', 'h2',\n        'h3', 'h4', 'ul', 'ol', 'li',\n        'strong', 'em', 'a', 'code', 'pre', \n        'blockquote'", verbose_name='Содержание поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(help_text='Одно-два предложения', max_length=200, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='edited_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее редактирование'),
        ),
    ]
