# Generated by Django 5.2.8 on 2026-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_post',
            field=models.ManyToManyField(related_name='users_liked', to='blog.post'),
        ),
    ]
