# Generated by Django 5.2.8 on 2026-02-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_liked_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='liked_post',
            new_name='liked_posts',
        ),
    ]
